// <auto-generated />
using System;
using Gma.Modules.Administration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gma.Modules.Administration.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260728074031_AddAdminResourceScope")]
    partial class AddAdminResourceScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gma.Modules.Administration.Persistence.Entities.AdminAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResourceScope")
                        .HasMaxLength(888)
                        .HasColumnType("nvarchar(888)");

                    b.Property<string>("ResourceScopeHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.HasIndex("ActorId", "CreatedAtUtc", "Id");

                    b.HasIndex("Operation", "CreatedAtUtc", "Id");

                    b.HasIndex("Permission", "CreatedAtUtc", "Id");

                    b.HasIndex("TenantId", "CreatedAtUtc", "Id");

                    b.HasIndex("TenantId", "ResourceScopeHash", "CreatedAtUtc", "Id");

                    b.ToTable("audit_entries", "admin");
                });
#pragma warning restore 612, 618
        }
    }
}
